<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>Mini Ajax File Upload Form</title>

    <!-- Google web fonts -->
    {{ stylesheet_link("http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700", false) }}

    <!-- The main CSS file -->
    {{ stylesheet_link("assets/css/style.css") }}
</head>

<body>

<form id="upload" method="post" action="upload.php" enctype="multipart/form-data">
    <div id="drop">
        Drop Here

        <a>Browse</a>
        <input type="file" name="upl" multiple />
    </div>

    <ul>
        <!-- The file uploads will be shown here -->
    </ul>

</form>

<!-- JavaScript Includes -->
{{ javascript_include("https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js", false) }}
{{ javascript_include("assets/js/jquery.knob.js") }}

<!-- jQuery File Upload Dependencies -->
{{ javascript_include("assets/js/jquery.ui.widget.js") }}
{{ javascript_include("assets/js/jquery.iframe-transport.js") }}
{{ javascript_include("assets/js/jquery.fileupload.js") }}

<!-- Our main JS file -->
{{ javascript_include("assets/js/script.js") }}

</body>
</html>